#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=fanfou-ontime
ARGS=
PIDFILE=/var/run/fanfou/ontime.pid

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

if [ -e "$PIDFILE" ]; then
  PID=$(cat "$PIDFILE")
  kill -0 "$PID"
  if [ $? != 0 ]; then
    PID=
  fi
else
  PID=
fi

case "$1" in
  start)
    stat_busy "Starting $DAEMON"
    export ONTIME_SETTINGS
    [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
    if [ $? = 0 ]; then
      add_daemon $DAEMON
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping $DAEMON"
    [ -n "$PID" ] && kill $PID &>/dev/null
    if [ $? = 0 ]; then
      rm_daemon $DAEMON
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  reload)
    stat_busy "Reloading $DAEMON"
    [ -n "$PID" ] && kill -USR1 $PID &>/dev/null
    if [ $? = 0]; then
      add_daemon $DAEMON
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
   
  *)
    echo "usage: $0 {start|stop|restart|reload}"
esac

exit 0
